/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FluencyBridgePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  savedHighlights: {},
  provider: "groq",
  apiKey: "",
  model: "llama-3.3-70b-versatile",
  customEndpoint: "https://api.groq.com/openai/v1/chat/completions",
  vocabularyPath: "Vocabulary.md",
  autoLogVocabulary: true,
  enableSlangAlerts: true,
  enableNuanceTips: true,
  nativeLanguage: "Turkish",
  targetLanguage: "English",
  highlightStyle: "decorations",
  highlightReplacedText: true,
  highlightFlaggedNuances: true
};
var PROVIDER_DEFAULTS = {
  groq: {
    endpoint: "https://api.groq.com/openai/v1/chat/completions",
    defaultModel: "llama-3.3-70b-versatile",
    placeholderKey: "gsk_..."
  },
  gemini: {
    endpoint: "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions",
    defaultModel: "gemini-2.0-flash",
    placeholderKey: "AIzaSy..."
  },
  openrouter: {
    endpoint: "https://openrouter.ai/api/v1/chat/completions",
    defaultModel: "meta-llama/llama-3.3-70b-instruct:free",
    placeholderKey: "sk-or-v1-..."
  },
  custom: {
    endpoint: "http://localhost:11434/v1/chat/completions",
    defaultModel: "llama3.1",
    placeholderKey: "Optional API Key"
  }
};

// src/settings.ts
var import_obsidian = require("obsidian");
var FluencyBridgeSettingTab = class extends import_obsidian.PluginSettingTab {
  plugin;
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Fluency Bridge Ayarlar\u0131" });
    containerEl.createEl("p", {
      text: "\u0130ki dilli yazma ak\u0131\u015F\u0131n\u0131z\u0131 bozmadan ba\u011Flamsal \xE7eviri, argo korumas\u0131 ve kelime kasas\u0131 y\xF6netimi.",
      cls: "setting-item-description"
    });
    new import_obsidian.Setting(containerEl).setName("Yapay Zeka Sa\u011Flay\u0131c\u0131s\u0131 (Provider)").setDesc("Kullanmak istedi\u011Finiz LLM API sa\u011Flay\u0131c\u0131s\u0131n\u0131 se\xE7in. H\u0131z i\xE7in Groq \xF6nerilir.").addDropdown((dropdown) => {
      dropdown.addOption("groq", "\u26A1 Groq (\xD6nerilen - Ultra H\u0131zl\u0131, \xDCcretsiz)").addOption("gemini", "\u2728 Google Gemini (Flash, Y\xFCksek Zeka, \xDCcretsiz)").addOption("openrouter", "\u{1F310} OpenRouter (Geni\u015F Model Yelpazesi)").addOption("custom", "\u{1F4BB} \xD6zel / Yerel (Ollama / Local REST)").setValue(this.plugin.settings.provider).onChange(async (val) => {
        this.plugin.settings.provider = val;
        const def = PROVIDER_DEFAULTS[this.plugin.settings.provider];
        this.plugin.settings.model = def.defaultModel;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    const providerDef = PROVIDER_DEFAULTS[this.plugin.settings.provider];
    new import_obsidian.Setting(containerEl).setName("API Anahtar\u0131").setDesc(`Se\xE7ili sa\u011Flay\u0131c\u0131 i\xE7in API anahtar\u0131n\u0131z (${this.plugin.settings.provider.toUpperCase()}).`).addText((text) => {
      text.setPlaceholder(providerDef.placeholderKey).setValue(this.plugin.settings.apiKey).onChange(async (val) => {
        this.plugin.settings.apiKey = val.trim();
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
    });
    const modelDesc = this.plugin.settings.provider === "groq" ? "Kullan\u0131lacak model ID. Groq i\xE7in: llama-3.3-70b-versatile (\xD6nerilen/Ak\u0131ll\u0131) veya qwen/qwen3.8-27b (Ultra H\u0131zl\u0131)" : "Kullan\u0131lacak model kimli\u011Fi (ID).";
    new import_obsidian.Setting(containerEl).setName("Model Ad\u0131").setDesc(modelDesc).addText((text) => {
      text.setPlaceholder(providerDef.defaultModel).setValue(this.plugin.settings.model).onChange(async (val) => {
        this.plugin.settings.model = val.trim();
        await this.plugin.saveSettings();
      });
    });
    if (this.plugin.settings.provider === "custom") {
      new import_obsidian.Setting(containerEl).setName("\xD6zel API U\xE7 Noktas\u0131 (Endpoint)").setDesc("OpenAI uyumlu tam POST URL (\xF6rn: http://localhost:11434/v1/chat/completions)").addText((text) => {
        text.setPlaceholder("http://localhost:11434/v1/chat/completions").setValue(this.plugin.settings.customEndpoint).onChange(async (val) => {
          this.plugin.settings.customEndpoint = val.trim();
          await this.plugin.saveSettings();
        });
      });
    }
    new import_obsidian.Setting(containerEl).setName("API Ba\u011Flant\u0131s\u0131n\u0131 Test Et").setDesc("Girdi\u011Finiz API anahtar\u0131n\u0131n ve modelin \xE7al\u0131\u015Ft\u0131\u011F\u0131n\u0131 do\u011Frulay\u0131n.").addButton((btn) => {
      btn.setButtonText("Ba\u011Flant\u0131y\u0131 Test Et").setCta().onClick(async () => {
        btn.setDisabled(true);
        btn.setButtonText("Test ediliyor...");
        const res = await this.plugin.llmClient.testConnection();
        btn.setDisabled(false);
        btn.setButtonText("Ba\u011Flant\u0131y\u0131 Test Et");
        if (res.success) {
          new import_obsidian.Notice(`\u2705 ${res.message}`);
        } else {
          new import_obsidian.Notice(`\u274C ${res.message}`, 6e3);
        }
      });
    });
    containerEl.createEl("h3", { text: "Metin \u0130\xE7i Vurgulama & Renklendirme" });
    new import_obsidian.Setting(containerEl).setName("Vurgulama Y\xF6ntemi (Highlight Style)").setDesc("D\xFCzeltilen yerlerin ve ipucu verilen kelimelerin nas\u0131l g\xF6sterilece\u011Fini belirleyin.").addDropdown((dropdown) => {
      dropdown.addOption("decorations", "\u2728 Do\u011Fal Edit\xF6r Vurgusu (CodeMirror 6 - S\u0131f\u0131r HTML, Dosyay\u0131 Kirletmez)").addOption("markdown", "\u270F\uFE0F Standart Markdown (==vurgu==)").addOption("none", "\u{1F6AB} Vurgusuz (Do\u011Frudan D\xFCz Metin)").setValue(this.plugin.settings.highlightStyle || "decorations").onChange(async (val) => {
        this.plugin.settings.highlightStyle = val;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("\xC7evrilen \u0130fadeyi Renklendir").setDesc("K\xF6\u015Feli parantezden d\xF6n\xFC\u015Ft\xFCr\xFClen hedef kelime/ifadeyi renkli olarak i\u015Faretle (hover ile orijinal T\xFCrk\xE7e ifade g\xF6r\xFCn\xFCr).").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.highlightReplacedText).onChange(async (val) => {
        this.plugin.settings.highlightReplacedText = val;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Uyar\u0131 & \u0130pucu Alan Kelimeleri \u0130\u015Faretle").setDesc("C\xFCmledeki yaz\u0131m hatalar\u0131 veya do\u011Fall\u0131k uyar\u0131s\u0131 alan kelimeleri dalgal\u0131 alt \xE7izgi ile i\u015Faretle (hover ile \xF6neri g\xF6r\xFCn\xFCr).").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.highlightFlaggedNuances).onChange(async (val) => {
        this.plugin.settings.highlightFlaggedNuances = val;
        await this.plugin.saveSettings();
      });
    });
    containerEl.createEl("h3", { text: "Kelime Kasas\u0131 & Uyar\u0131lar" });
    new import_obsidian.Setting(containerEl).setName("Kelime Kasas\u0131 Dosyas\u0131 (Vocabulary Path)").setDesc("\xC7evrilen ve \xF6\u011Frenilen kelimelerin otomatik eklenece\u011Fi markdown dosyas\u0131.").addText((text) => {
      text.setPlaceholder("Vocabulary.md").setValue(this.plugin.settings.vocabularyPath).onChange(async (val) => {
        this.plugin.settings.vocabularyPath = val.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Kelimeyi Otomatik Kaydet").setDesc("De\u011Fi\u015Ftirilen her deyim ve kelimeyi otomatik olarak kelime k\xFCt\xFC\u011F\xFCne tablo olarak ekle.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.autoLogVocabulary).onChange(async (val) => {
        this.plugin.settings.autoLogVocabulary = val;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Yaz\u0131m ve Do\u011Fall\u0131k \xD6nerileri (Fluency & Nuance Tips)").setDesc("C\xFCmlenizdeki olas\u0131 yaz\u0131m hatalar\u0131 (typo), daha do\u011Fal alternatif ifadeler ve ba\u011Flamsal n\xFCanslar hakk\u0131nda yap\u0131c\u0131 ipu\xE7lar\u0131 g\xF6ster.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.enableNuanceTips ?? true).onChange(async (val) => {
        this.plugin.settings.enableNuanceTips = val;
        this.plugin.settings.enableSlangAlerts = val;
        await this.plugin.saveSettings();
      });
    });
  }
};

// src/llm/client.ts
var LLMClient = class {
  settings;
  constructor(settings) {
    this.settings = settings;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  getEndpoint() {
    if (this.settings.provider === "custom" && this.settings.customEndpoint.trim()) {
      return this.settings.customEndpoint.trim();
    }
    return PROVIDER_DEFAULTS[this.settings.provider].endpoint;
  }
  getModel() {
    if (this.settings.model.trim()) {
      return this.settings.model.trim();
    }
    return PROVIDER_DEFAULTS[this.settings.provider].defaultModel;
  }
  async testConnection() {
    try {
      const endpoint = this.getEndpoint();
      const model = this.getModel();
      const apiKey = this.settings.apiKey.trim();
      if (!apiKey && this.settings.provider !== "custom") {
        return {
          success: false,
          message: "API Key bo\u015F olamaz. L\xFCtfen ge\xE7erli bir anahtar girin."
        };
      }
      const headers = {
        "Content-Type": "application/json"
      };
      if (apiKey) {
        headers["Authorization"] = `Bearer ${apiKey}`;
      }
      if (this.settings.provider === "openrouter") {
        headers["HTTP-Referer"] = "https://obsidian.md";
        headers["X-Title"] = "Obsidian Fluency Bridge";
      }
      const res = await fetch(endpoint, {
        method: "POST",
        headers,
        body: JSON.stringify({
          model,
          messages: [{ role: "user", content: "Reply with 'OK' if you hear me." }],
          max_tokens: 100,
          temperature: 0.1
        })
      });
      if (!res.ok) {
        const errorText = await res.text();
        return {
          success: false,
          message: `API Hatas\u0131 (${res.status}): ${errorText.slice(0, 200)}`
        };
      }
      return {
        success: true,
        message: `Ba\u011Flant\u0131 ba\u015Far\u0131l\u0131! (${this.settings.provider.toUpperCase()} - ${model})`
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { success: false, message: `Ba\u011Flant\u0131 kurulamad\u0131: ${msg}` };
    }
  }
  async translateInFlow(expression, contextSentence) {
    const endpoint = this.getEndpoint();
    const model = this.getModel();
    const apiKey = this.settings.apiKey.trim();
    if (!apiKey && this.settings.provider !== "custom") {
      throw new Error(
        "Fluency Bridge API Anahtar\u0131 ayarlanmam\u0131\u015F! L\xFCtfen Eklenti Ayarlar\u0131ndan API anahtar\u0131n\u0131z\u0131 girin."
      );
    }
    const systemPrompt = `You are Fluency Bridge, an expert bilingual writing coach specialized in helping users write natural, fluent, and idiomatic ${this.settings.targetLanguage} while thinking in ${this.settings.nativeLanguage}.

The user is writing in ${this.settings.targetLanguage}, but hit a mental roadblock and wrote a phrase or word in [brackets] in ${this.settings.nativeLanguage}.

Your goals:
1. Provide the most natural, idiomatic, and contextually accurate ${this.settings.targetLanguage} replacement that fits seamlessly into the sentence's grammar, rhythm, and tone.
2. CONSTRUCTIVE FLUENCY & NUANCE COACHING:
   - Review the surrounding sentence for any typos (misspellings), unnatural collocations, or phrasing that could be expressed more clearly or idiomatically.
   - If there are typos or phrases that would sound significantly more natural (e.g. "hearth" instead of "heart", "make research" instead of "do research"):
     a) Provide a friendly, concise, and constructive tip in Turkish in the "feedback" field mentioning ALL issues found (e.g. "\u0130pucu: 'hearth' yerine 'heart'; 'make research' yerine 'do research' kullan\u0131m\u0131 daha do\u011Fald\u0131r.").
     b) Populate the "flaggedItems" ARRAY with ONE entry for EVERY separate issue in the sentence. Never stop at the first one; if the sentence has two typos, return two entries. Each entry has:
        - "original": the EXACT substring as it appears in the user's sentence, copied character-for-character (e.g. "hearth" or "make research"). Keep it as short as possible (usually a single word) so it can be located precisely.
        - "suggestion": the improved target language word or phrase (e.g. "heart" or "do research")
        - "reason": concise reason in Turkish (e.g. "Yaz\u0131m hatas\u0131" or "Do\u011Fal e\u015Fdizim")
     c) Do NOT flag the bracketed expression itself; it is being replaced.
   - If the sentence is already completely natural and error-free, set "feedback" to null and "flaggedItems" to [].
   - Do NOT lecture or moralize about tone or intent. Focus purely on constructive writing polish, clarity, and linguistic nuances.
3. Extract the key vocabulary item (word or collocation phrase) to add to the user's active vocabulary list.

You MUST respond strictly with valid JSON conforming to this schema (no markdown fences, no extra text):
{
  "replacement": "exact replacement string for inside or including the brackets",
  "feedback": "Optional concise, constructive tip in Turkish about typos, phrasing improvements, or nuance, or null",
  "flaggedItems": [
    {
      "original": "exact word or phrase from the sentence that has a typo or unnatural usage",
      "suggestion": "improved word or phrase",
      "reason": "k\u0131sa a\xE7\u0131klama (\xF6rn: Yaz\u0131m hatas\u0131 veya Do\u011Fal e\u015Fdizim)"
    }
  ],
  "vocabItem": {
    "term": "the key target language word or idiom",
    "definition": "T\xFCrk\xE7e anlam\u0131 ve kullan\u0131m notu",
    "example": "the full sentence with the replacement applied"
  }
}`;
    const userPrompt = `Context Sentence: "${contextSentence}"
Bracketed/Target Expression: "${expression}"

Provide the natural replacement to substitute the bracketed text directly.`;
    const headers = {
      "Content-Type": "application/json"
    };
    if (apiKey) {
      headers["Authorization"] = `Bearer ${apiKey}`;
    }
    if (this.settings.provider === "openrouter") {
      headers["HTTP-Referer"] = "https://obsidian.md";
      headers["X-Title"] = "Obsidian Fluency Bridge";
    }
    const payload = {
      model,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt }
      ],
      temperature: 0.2,
      max_tokens: 1024,
      response_format: { type: "json_object" }
    };
    const res = await fetch(endpoint, {
      method: "POST",
      headers,
      body: JSON.stringify(payload)
    });
    if (!res.ok) {
      const errText = await res.text();
      throw new Error(`LLM API Hatas\u0131 [${res.status}]: ${errText.slice(0, 300)}`);
    }
    const data = await res.json();
    const content = data.choices?.[0]?.message?.content;
    if (!content) {
      throw new Error("Modelden bo\u015F yan\u0131t al\u0131nd\u0131.");
    }
    let parsed;
    try {
      parsed = JSON.parse(content);
    } catch {
      const cleaned = content.replace(/```json\s*/g, "").replace(/```\s*$/g, "").trim();
      parsed = JSON.parse(cleaned);
    }
    parsed.feedback = parsed.feedback || parsed.warning || null;
    const rawItems = [
      ...Array.isArray(parsed.flaggedItems) ? parsed.flaggedItems : [],
      ...parsed.flaggedItem ? [parsed.flaggedItem] : []
    ];
    const seen = /* @__PURE__ */ new Set();
    parsed.flaggedItems = [];
    for (const raw of rawItems) {
      if (!raw || typeof raw !== "object") continue;
      const item = raw;
      const original = typeof item.original === "string" ? item.original.trim() : "";
      if (!original || !item.suggestion) continue;
      const key = original.toLowerCase();
      if (seen.has(key)) continue;
      seen.add(key);
      parsed.flaggedItems.push({
        original,
        suggestion: String(item.suggestion),
        reason: item.reason ? String(item.reason) : ""
      });
    }
    parsed.flaggedItem = parsed.flaggedItems[0] ?? null;
    return parsed;
  }
};

// src/services/contextParser.ts
var ContextParser = class {
  /**
   * Extracts the target expression and surrounding context sentence from the active editor.
   */
  static extractTarget(editor) {
    const selection = editor.getSelection();
    const cursor = editor.getCursor();
    const lineNum = cursor.line;
    const lineText = editor.getLine(lineNum);
    if (selection && selection.trim().length > 0) {
      const from = editor.getCursor("from");
      const to = editor.getCursor("to");
      return {
        rawExpression: selection.trim(),
        fullSentence: lineText.trim() || selection.trim(),
        replaceRange: { from, to }
      };
    }
    const regex = /\[([^\]]+)\]/g;
    let match;
    const matches = [];
    while ((match = regex.exec(lineText)) !== null) {
      const start = match.index;
      const end = match.index + match[0].length;
      const innerContent = match[1];
      let distance = 0;
      if (cursor.ch < start) {
        distance = start - cursor.ch;
      } else if (cursor.ch > end) {
        distance = cursor.ch - end;
      } else {
        distance = 0;
      }
      matches.push({
        fullMatch: match[0],
        innerContent,
        start,
        end,
        distanceToCursor: distance
      });
    }
    if (matches.length === 0) {
      return null;
    }
    matches.sort((a, b) => a.distanceToCursor - b.distanceToCursor);
    const bestMatch = matches[0];
    return {
      rawExpression: bestMatch.innerContent,
      fullSentence: lineText.trim(),
      replaceRange: {
        from: { line: lineNum, ch: bestMatch.start },
        to: { line: lineNum, ch: bestMatch.end }
      }
    };
  }
};

// src/services/vocabulary.ts
var import_obsidian2 = require("obsidian");
var VocabularyManager = class {
  app;
  settings;
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  async logItem(result, originalSentence) {
    if (!this.settings.autoLogVocabulary || !result.vocabItem) {
      return false;
    }
    try {
      const filePath = (0, import_obsidian2.normalizePath)(this.settings.vocabularyPath.trim() || "Vocabulary.md");
      const folderPath = filePath.substring(0, filePath.lastIndexOf("/"));
      if (folderPath && !await this.app.vault.adapter.exists(folderPath)) {
        await this.app.vault.createFolder(folderPath);
      }
      const dateStr = (/* @__PURE__ */ new Date()).toISOString().slice(0, 16).replace("T", " ");
      const term = result.vocabItem.term.replace(/\|/g, "\\|");
      const def = result.vocabItem.definition.replace(/\|/g, "\\|");
      const sentence = (result.vocabItem.example || originalSentence).replace(/\|/g, "\\|").trim();
      const newRow = `| ${dateStr} | **${term}** | ${def} | ${sentence} |
`;
      const existingFile = this.app.vault.getAbstractFileByPath(filePath);
      if (existingFile instanceof import_obsidian2.TFile) {
        await this.app.vault.append(existingFile, newRow);
      } else {
        const initialContent = `# \u{1F4DA} Active Vocabulary Deck (Fluency Bridge)

Otomatik olu\u015Fturulan aktif kelime ve deyimler listesi.

| Tarih | \u0130fade / Kelime | Anlam & Not | Ba\u011Flamsal C\xFCmle |
| :--- | :--- | :--- | :--- |
` + newRow;
        await this.app.vault.create(filePath, initialContent);
      }
      return true;
    } catch (err) {
      console.error("[Fluency Bridge] Kelime kasas\u0131na kaydedilirken hata olu\u015Ftu:", err);
      return false;
    }
  }
};

// src/services/highlightManager.ts
var import_state = require("@codemirror/state");
var import_view = require("@codemirror/view");
var import_obsidian3 = require("obsidian");
var addFluencyDecorations = import_state.StateEffect.define();
var clearFluencyDecorations = import_state.StateEffect.define();
function normalizeForMatch(text) {
  return (text || "").trim().replace(/^[^\p{L}\p{N}]+|[^\p{L}\p{N}]+$/gu, "").replace(/\s+/g, " ").toLowerCase();
}
function matchesSuggestion(text, suggestion) {
  const target = normalizeForMatch(suggestion ?? "");
  return target.length > 0 && normalizeForMatch(text) === target;
}
function buildMark(spec) {
  return import_view.Decoration.mark({
    class: `fb-highlight fb-${spec.type}`,
    attributes: {
      title: spec.tooltip
    },
    suggestion: spec.suggestion
  });
}
var fluencyHighlightField = import_state.StateField.define({
  create() {
    return import_view.Decoration.none;
  },
  update(decorations, tr) {
    if (tr.docChanged) {
      const isNuance = (value) => (value.spec.class ?? "").includes("fb-nuance");
      const survivors = [];
      const iter = decorations.iter();
      while (iter.value) {
        if (isNuance(iter.value)) {
          const spec = iter.value.spec;
          const from = tr.changes.mapPos(iter.from, 1);
          const to = tr.changes.mapPos(iter.to, -1);
          if (to > from) {
            const newText = tr.newDoc.sliceString(from, to);
            const oldText = tr.startState.doc.sliceString(iter.from, iter.to);
            const fixed = spec.suggestion ? matchesSuggestion(newText, spec.suggestion) : newText !== oldText;
            if (!fixed) survivors.push(iter.value.range(from, to));
          }
        }
        iter.next();
      }
      decorations = decorations.update({ filter: (_from, _to, value) => !isNuance(value) }).map(tr.changes).update({ add: survivors, sort: true });
    }
    for (const effect of tr.effects) {
      if (effect.is(addFluencyDecorations)) {
        const marks = effect.value.filter((spec) => spec.to > spec.from).map((spec) => buildMark(spec).range(spec.from, spec.to));
        decorations = decorations.update({
          add: marks,
          sort: true
        });
      } else if (effect.is(clearFluencyDecorations)) {
        decorations = import_view.Decoration.none;
      }
    }
    return decorations;
  },
  provide: (f) => import_view.EditorView.decorations.from(f)
});
function extractStoredHighlights(state) {
  const set = state.field(fluencyHighlightField, false);
  const out = [];
  if (!set) return out;
  const iter = set.iter();
  while (iter.value) {
    const spec = iter.value.spec;
    out.push({
      from: iter.from,
      to: iter.to,
      text: state.doc.sliceString(iter.from, iter.to),
      type: spec.class?.includes("fb-nuance") ? "nuance" : "replaced",
      tooltip: spec.attributes?.title ?? "",
      suggestion: spec.suggestion
    });
    iter.next();
  }
  return out;
}
function resolveStoredHighlights(docText, stored) {
  const resolved = [];
  for (const h of stored) {
    if (!h.text) continue;
    let from = -1;
    if (docText.slice(h.from, h.from + h.text.length) === h.text) {
      from = h.from;
    } else {
      let best = -1;
      let bestDist = Infinity;
      let idx = docText.indexOf(h.text);
      while (idx !== -1) {
        const dist = Math.abs(idx - h.from);
        if (dist < bestDist) {
          best = idx;
          bestDist = dist;
        }
        idx = docText.indexOf(h.text, idx + 1);
      }
      from = best;
    }
    if (from < 0) continue;
    resolved.push({
      from,
      to: from + h.text.length,
      type: h.type,
      tooltip: h.tooltip,
      suggestion: h.suggestion
    });
  }
  return resolved;
}
function handleHighlightUpdate(update, onChange) {
  const touchedHighlights = update.transactions.some(
    (tr) => tr.effects.some((e) => e.is(addFluencyDecorations) || e.is(clearFluencyDecorations))
  );
  if (!update.docChanged && !touchedHighlights) return;
  const before = update.startState.field(fluencyHighlightField, false)?.size ?? 0;
  const after = update.state.field(fluencyHighlightField, false)?.size ?? 0;
  if (before === 0 && after === 0) return;
  if (update.docChanged && !touchedHighlights) {
    const oldLen = update.startState.doc.length;
    let replacedWholeDoc = false;
    update.changes.iterChangedRanges((fromA, toA) => {
      if (oldLen > 0 && fromA === 0 && toA === oldLen) replacedWholeDoc = true;
    });
    if (replacedWholeDoc) return;
  }
  const file = update.state.field(import_obsidian3.editorInfoField, false)?.file;
  if (!file) return;
  onChange(file.path, extractStoredHighlights(update.state));
}
function createHighlightPersistence(onChange) {
  return import_view.EditorView.updateListener.of((update) => handleHighlightUpdate(update, onChange));
}
function getEditorView(editor) {
  if (!editor) return null;
  if (editor.cm instanceof import_view.EditorView) {
    return editor.cm;
  }
  if (editor.editor?.cm instanceof import_view.EditorView) {
    return editor.editor.cm;
  }
  if (editor.cm && typeof editor.cm.dispatch === "function") {
    return editor.cm;
  }
  return null;
}
var HighlightManager = class {
  static escapeRegex(text) {
    return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  }
  /**
   * Finds EVERY occurrence of a word/phrase on a line.
   * Tolerates different whitespace, surrounding punctuation and letter case.
   * Whole-word matches are preferred; a plain substring match is used only if none exist.
   */
  static findAllInLine(lineText, word) {
    const cleaned = (word || "").trim().replace(/^[^\p{L}\p{N}]+|[^\p{L}\p{N}]+$/gu, "");
    if (!cleaned) return [];
    const body = cleaned.split(/\s+/).map((part) => this.escapeRegex(part)).join("\\s+");
    const collect = (pattern) => {
      const found = [];
      let match;
      while ((match = pattern.exec(lineText)) !== null) {
        if (match[0].length === 0) {
          pattern.lastIndex++;
          continue;
        }
        found.push({ start: match.index, end: match.index + match[0].length });
      }
      return found;
    };
    const wholeWord = collect(
      new RegExp(`(?<![\\p{L}\\p{N}_])${body}(?![\\p{L}\\p{N}_])`, "giu")
    );
    if (wholeWord.length > 0) return wholeWord;
    return collect(new RegExp(body, "giu"));
  }
  /**
   * Collects all distinct flagged items from a result (new array form + legacy single form).
   */
  static collectFlaggedItems(result) {
    const all = [
      ...result.flaggedItems ?? [],
      ...result.flaggedItem ? [result.flaggedItem] : []
    ];
    const seen = /* @__PURE__ */ new Set();
    const unique = [];
    for (const item of all) {
      const key = (item?.original ?? "").trim().toLowerCase();
      if (!key || seen.has(key)) continue;
      seen.add(key);
      unique.push(item);
    }
    return unique;
  }
  /**
   * Computes the nuance decorations for a line: every occurrence of every flagged item,
   * never overlapping the replaced span or each other.
   */
  static computeNuanceSpecs(lineText, lineStartOffset, items, occupied) {
    const specs = [];
    const taken = [...occupied];
    const overlaps = (s, e) => taken.some((t) => s < t.end && e > t.start);
    for (const item of items) {
      const tooltip = `\u{1F4A1} \xD6neri: ${item.suggestion} (${item.reason || "\u0130pucu"})`;
      for (const m of this.findAllInLine(lineText, item.original)) {
        if (overlaps(m.start, m.end)) continue;
        taken.push(m);
        specs.push({
          from: lineStartOffset + m.start,
          to: lineStartOffset + m.end,
          type: "nuance",
          tooltip,
          suggestion: item.suggestion
        });
      }
    }
    return specs;
  }
  /**
   * Applies the translation to the editor text cleanly (ZERO HTML tags)
   * and dispatches visual CodeMirror 6 editor decorations for replaced & nuance words.
   */
  static applyToEditor(editor, target, result, settings) {
    const style = settings.highlightStyle || "decorations";
    const highlightReplaced = settings.highlightReplacedText ?? true;
    const highlightNuance = settings.highlightFlaggedNuances ?? true;
    let textToInsert = result.replacement;
    if (style === "markdown" && highlightReplaced) {
      textToInsert = `==${result.replacement}==`;
    }
    const fromOffset = editor.posToOffset(target.replaceRange.from);
    editor.replaceRange(
      textToInsert,
      target.replaceRange.from,
      target.replaceRange.to
    );
    const toOffset = fromOffset + textToInsert.length;
    const newCursorPos = editor.offsetToPos(toOffset);
    editor.setCursor(newCursorPos);
    if (style === "decorations") {
      const editorView = getEditorView(editor);
      if (editorView) {
        const decos = [];
        if (highlightReplaced) {
          decos.push({
            from: fromOffset,
            to: toOffset,
            type: "replaced",
            tooltip: `Orijinal: [${target.rawExpression}]`
          });
        }
        const items = this.collectFlaggedItems(result);
        if (highlightNuance && items.length > 0) {
          const lineNum = target.replaceRange.from.line;
          const lineText = editor.getLine(lineNum);
          const lineStartOffset = editor.posToOffset({ line: lineNum, ch: 0 });
          const replacedSpan = {
            start: target.replaceRange.from.ch,
            end: target.replaceRange.from.ch + textToInsert.length
          };
          decos.push(
            ...this.computeNuanceSpecs(lineText, lineStartOffset, items, [replacedSpan])
          );
        }
        if (decos.length > 0) {
          editorView.dispatch({
            effects: [addFluencyDecorations.of(decos)]
          });
        }
      }
    }
    return { cursorCh: newCursorPos.ch, line: newCursorPos.line };
  }
  /**
   * Re-applies persisted highlights to an editor (used after a note is reopened).
   * Returns the number of highlights applied; does nothing if the editor already shows highlights.
   */
  static restoreToEditor(editor, stored) {
    const editorView = getEditorView(editor);
    if (!editorView || stored.length === 0) return 0;
    const current = editorView.state.field(fluencyHighlightField, false);
    if (!current || current.size > 0) return 0;
    const specs = resolveStoredHighlights(editorView.state.doc.toString(), stored);
    if (specs.length === 0) return 0;
    editorView.dispatch({ effects: [addFluencyDecorations.of(specs)] });
    return specs.length;
  }
  /**
   * Clears CodeMirror 6 editor decorations and any legacy HTML marks.
   */
  static clearHighlights(editor) {
    const editorView = getEditorView(editor);
    if (editorView) {
      editorView.dispatch({
        effects: [clearFluencyDecorations.of()]
      });
    }
    const content = editor.getValue();
    const regex = /<mark\s+class="[^"]*fb-(?:highlight|replaced|nuance)[^"]*"[^>]*>([\s\S]*?)<\/mark>/gi;
    let legacyRemovedCount = 0;
    const cleaned = content.replace(regex, (_match, group1) => {
      legacyRemovedCount++;
      return group1;
    });
    if (legacyRemovedCount > 0) {
      editor.setValue(cleaned);
    }
    return { legacyRemovedCount };
  }
};

// src/main.ts
var FluencyBridgePlugin = class extends import_obsidian4.Plugin {
  settings = DEFAULT_SETTINGS;
  llmClient = new LLMClient(this.settings);
  vocabManager = new VocabularyManager(this.app, this.settings);
  persistTimer = null;
  async onload() {
    await this.loadSettings();
    this.llmClient = new LLMClient(this.settings);
    this.vocabManager = new VocabularyManager(this.app, this.settings);
    this.registerEditorExtension([
      fluencyHighlightField,
      createHighlightPersistence((path, highlights) => this.rememberHighlights(path, highlights))
    ]);
    this.addSettingTab(new FluencyBridgeSettingTab(this.app, this));
    this.addCommand({
      id: "replace-in-flow-expression",
      name: "Replace In-Flow Expression (Ak\u0131\u015F \u0130\xE7i \u0130fadeyi \xC7evir)",
      editorCallback: async (editor, _ctx) => {
        await this.handleInFlowTranslation(editor);
      },
      hotkeys: [
        {
          modifiers: ["Mod", "Shift"],
          key: "E"
        }
      ]
    });
    this.addCommand({
      id: "clear-fluency-highlights",
      name: "Clear Fluency Highlights in Active Note (Aktif Nottaki Vurgular\u0131 Temizle)",
      editorCallback: (editor, _ctx) => {
        this.handleClearHighlights(editor);
      },
      hotkeys: [
        {
          modifiers: ["Mod", "Shift"],
          key: "H"
        }
      ]
    });
    this.registerEvent(this.app.workspace.on("file-open", () => this.scheduleRestore()));
    this.registerEvent(this.app.workspace.on("active-leaf-change", () => this.scheduleRestore()));
    this.registerEvent(this.app.workspace.on("layout-change", () => this.scheduleRestore()));
    this.app.workspace.onLayoutReady(() => this.scheduleRestore());
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        const saved = this.settings.savedHighlights;
        if (saved[oldPath]) {
          saved[file.path] = saved[oldPath];
          delete saved[oldPath];
          this.queuePersist();
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (this.settings.savedHighlights[file.path]) {
          delete this.settings.savedHighlights[file.path];
          this.queuePersist();
        }
      })
    );
    console.log("[Fluency Bridge v0.2.0] Eklenti ba\u015Far\u0131yla y\xFCklendi.");
  }
  onunload() {
    if (this.persistTimer !== null) {
      window.clearTimeout(this.persistTimer);
      this.persistTimer = null;
      void this.saveData(this.settings);
    }
    console.log("[Fluency Bridge] Eklenti devreden \xE7\u0131kar\u0131ld\u0131.");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    this.settings.savedHighlights = { ...this.settings.savedHighlights ?? {} };
    if (this.llmClient) {
      this.llmClient.updateSettings(this.settings);
    }
    if (this.vocabManager) {
      this.vocabManager.updateSettings(this.settings);
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.llmClient.updateSettings(this.settings);
    this.vocabManager.updateSettings(this.settings);
  }
  /** Called by the editor extension on every change of a note's highlights. */
  rememberHighlights(path, highlights) {
    if (highlights.length === 0) {
      delete this.settings.savedHighlights[path];
    } else {
      this.settings.savedHighlights[path] = highlights;
    }
    this.queuePersist();
  }
  /** In-memory state is always current; only the disk write is debounced. */
  queuePersist() {
    if (this.persistTimer !== null) window.clearTimeout(this.persistTimer);
    this.persistTimer = window.setTimeout(() => {
      this.persistTimer = null;
      void this.saveData(this.settings);
    }, 600);
  }
  /** The note content may still be loading right after open, so retry a few times (idempotent). */
  scheduleRestore() {
    for (const delay of [0, 150, 500, 1200]) {
      window.setTimeout(() => this.restoreOpenNotes(), delay);
    }
  }
  restoreOpenNotes() {
    this.app.workspace.iterateAllLeaves((leaf) => {
      const view = leaf.view;
      if (!(view instanceof import_obsidian4.MarkdownView) || !view.file) return;
      const stored = this.settings.savedHighlights[view.file.path];
      if (!stored || stored.length === 0) return;
      HighlightManager.restoreToEditor(view.editor, stored);
    });
  }
  async handleInFlowTranslation(editor) {
    const target = ContextParser.extractTarget(editor);
    if (!target) {
      new import_obsidian4.Notice(
        "Fluency Bridge: \xC7evrilecek ifade bulunamad\u0131! L\xFCtfen bir ifadeyi [k\xF6\u015Feli parantez] i\xE7ine al\u0131n veya metni se\xE7in.",
        4e3
      );
      return;
    }
    const pendingNotice = new import_obsidian4.Notice(
      `Fluency Bridge: [${target.rawExpression}] ba\u011Flama g\xF6re d\xF6n\xFC\u015Ft\xFCr\xFCl\xFCyor...`,
      0
    );
    try {
      const startTime = performance.now();
      const result = await this.llmClient.translateInFlow(
        target.rawExpression,
        target.fullSentence
      );
      const durationMs = Math.round(performance.now() - startTime);
      pendingNotice.hide();
      if (!result.replacement) {
        new import_obsidian4.Notice("Fluency Bridge: Modelden ge\xE7erli bir kar\u015F\u0131l\u0131k al\u0131namad\u0131.", 4e3);
        return;
      }
      HighlightManager.applyToEditor(editor, target, result, this.settings);
      const tip = result.feedback || result.warning;
      const enableTips = this.settings.enableNuanceTips ?? this.settings.enableSlangAlerts ?? true;
      if (enableTips && tip) {
        new import_obsidian4.Notice(`\u{1F4A1} \u0130pucu: ${tip}`, 8e3);
      } else {
        new import_obsidian4.Notice(`\u2713 Ak\u0131\u015Fa uyarland\u0131 (${durationMs}ms)`, 2e3);
      }
      if (this.settings.autoLogVocabulary) {
        await this.vocabManager.logItem(result, target.fullSentence);
      }
    } catch (err) {
      pendingNotice.hide();
      const errorMsg = err instanceof Error ? err.message : String(err);
      new import_obsidian4.Notice(`Fluency Bridge Hatas\u0131: ${errorMsg}`, 7e3);
      console.error("[Fluency Bridge Error]", err);
    }
  }
  handleClearHighlights(editor) {
    const { legacyRemovedCount } = HighlightManager.clearHighlights(editor);
    if (legacyRemovedCount > 0) {
      new import_obsidian4.Notice(`\u2713 Fluency Bridge: G\xF6rsel vurgular ve ${legacyRemovedCount} adet eski etiket temizlendi.`, 3e3);
    } else {
      new import_obsidian4.Notice("\u2713 Fluency Bridge: G\xF6rsel vurgulamalar temizlendi.", 2500);
    }
  }
};
