/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FluencyBridgePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  provider: "groq",
  apiKey: "",
  model: "openai/gpt-oss-120b",
  customEndpoint: "https://api.groq.com/openai/v1/chat/completions",
  vocabularyPath: "Vocabulary.md",
  autoLogVocabulary: true,
  enableNuanceTips: true,
  nativeLanguage: "Turkish",
  targetLanguage: "English"
};
var PROVIDER_DEFAULTS = {
  groq: {
    endpoint: "https://api.groq.com/openai/v1/chat/completions",
    defaultModel: "openai/gpt-oss-120b",
    placeholderKey: "gsk_..."
  },
  gemini: {
    endpoint: "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions",
    defaultModel: "gemini-2.0-flash",
    placeholderKey: "AIzaSy..."
  },
  openrouter: {
    endpoint: "https://openrouter.ai/api/v1/chat/completions",
    defaultModel: "meta-llama/llama-3.3-70b-instruct:free",
    placeholderKey: "sk-or-v1-..."
  },
  custom: {
    endpoint: "http://localhost:11434/v1/chat/completions",
    defaultModel: "llama3.1",
    placeholderKey: "Optional API Key"
  }
};

// src/settings.ts
var import_obsidian = require("obsidian");
var FluencyBridgeSettingTab = class extends import_obsidian.PluginSettingTab {
  plugin;
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Fluency Bridge Ayarlar\u0131" });
    containerEl.createEl("p", {
      text: "\u0130ki dilli yazma ak\u0131\u015F\u0131n\u0131z\u0131 bozmadan ba\u011Flamsal \xE7eviri, argo korumas\u0131 ve kelime kasas\u0131 y\xF6netimi.",
      cls: "setting-item-description"
    });
    new import_obsidian.Setting(containerEl).setName("Yapay Zeka Sa\u011Flay\u0131c\u0131s\u0131 (Provider)").setDesc("Kullanmak istedi\u011Finiz LLM API sa\u011Flay\u0131c\u0131s\u0131n\u0131 se\xE7in. H\u0131z i\xE7in Groq \xF6nerilir.").addDropdown((dropdown) => {
      dropdown.addOption("groq", "\u26A1 Groq (\xD6nerilen - Ultra H\u0131zl\u0131, \xDCcretsiz)").addOption("gemini", "\u2728 Google Gemini (Flash, Y\xFCksek Zeka, \xDCcretsiz)").addOption("openrouter", "\u{1F310} OpenRouter (Geni\u015F Model Yelpazesi)").addOption("custom", "\u{1F4BB} \xD6zel / Yerel (Ollama / Local REST)").setValue(this.plugin.settings.provider).onChange(async (val) => {
        this.plugin.settings.provider = val;
        const def = PROVIDER_DEFAULTS[this.plugin.settings.provider];
        this.plugin.settings.model = def.defaultModel;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    const providerDef = PROVIDER_DEFAULTS[this.plugin.settings.provider];
    new import_obsidian.Setting(containerEl).setName("API Anahtar\u0131").setDesc(`Se\xE7ili sa\u011Flay\u0131c\u0131 i\xE7in API anahtar\u0131n\u0131z (${this.plugin.settings.provider.toUpperCase()}).`).addText((text) => {
      text.setPlaceholder(providerDef.placeholderKey).setValue(this.plugin.settings.apiKey).onChange(async (val) => {
        this.plugin.settings.apiKey = val.trim();
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
    });
    const modelDesc = this.plugin.settings.provider === "groq" ? "Kullan\u0131lacak model ID. Groq i\xE7in: openai/gpt-oss-120b (\xD6nerilen/Ak\u0131ll\u0131) veya qwen/qwen3.8-27b (Ultra H\u0131zl\u0131 - 70ms)" : "Kullan\u0131lacak model kimli\u011Fi (ID).";
    new import_obsidian.Setting(containerEl).setName("Model Ad\u0131").setDesc(modelDesc).addText((text) => {
      text.setPlaceholder(providerDef.defaultModel).setValue(this.plugin.settings.model).onChange(async (val) => {
        this.plugin.settings.model = val.trim();
        await this.plugin.saveSettings();
      });
    });
    if (this.plugin.settings.provider === "custom") {
      new import_obsidian.Setting(containerEl).setName("\xD6zel API U\xE7 Noktas\u0131 (Endpoint)").setDesc("OpenAI uyumlu tam POST URL (\xF6rn: http://localhost:11434/v1/chat/completions)").addText((text) => {
        text.setPlaceholder("http://localhost:11434/v1/chat/completions").setValue(this.plugin.settings.customEndpoint).onChange(async (val) => {
          this.plugin.settings.customEndpoint = val.trim();
          await this.plugin.saveSettings();
        });
      });
    }
    new import_obsidian.Setting(containerEl).setName("API Ba\u011Flant\u0131s\u0131n\u0131 Test Et").setDesc("Girdi\u011Finiz API anahtar\u0131n\u0131n ve modelin \xE7al\u0131\u015Ft\u0131\u011F\u0131n\u0131 do\u011Frulay\u0131n.").addButton((btn) => {
      btn.setButtonText("Ba\u011Flant\u0131y\u0131 Test Et").setCta().onClick(async () => {
        btn.setDisabled(true);
        btn.setButtonText("Test ediliyor...");
        const res = await this.plugin.llmClient.testConnection();
        btn.setDisabled(false);
        btn.setButtonText("Ba\u011Flant\u0131y\u0131 Test Et");
        if (res.success) {
          new import_obsidian.Notice(`\u2705 ${res.message}`);
        } else {
          new import_obsidian.Notice(`\u274C ${res.message}`, 6e3);
        }
      });
    });
    containerEl.createEl("h3", { text: "Kelime Kasas\u0131 & Uyar\u0131lar" });
    new import_obsidian.Setting(containerEl).setName("Kelime Kasas\u0131 Dosyas\u0131 (Vocabulary Path)").setDesc("\xC7evrilen ve \xF6\u011Frenilen kelimelerin otomatik eklenece\u011Fi markdown dosyas\u0131.").addText((text) => {
      text.setPlaceholder("Vocabulary.md").setValue(this.plugin.settings.vocabularyPath).onChange(async (val) => {
        this.plugin.settings.vocabularyPath = val.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Kelimeyi Otomatik Kaydet").setDesc("De\u011Fi\u015Ftirilen her deyim ve kelimeyi otomatik olarak kelime k\xFCt\xFC\u011F\xFCne tablo olarak ekle.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.autoLogVocabulary).onChange(async (val) => {
        this.plugin.settings.autoLogVocabulary = val;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Yaz\u0131m ve Do\u011Fall\u0131k \xD6nerileri (Fluency & Nuance Tips)").setDesc("C\xFCmlenizdeki olas\u0131 yaz\u0131m hatalar\u0131 (typo), daha do\u011Fal alternatif ifadeler ve ba\u011Flamsal n\xFCanslar hakk\u0131nda yap\u0131c\u0131 ipu\xE7lar\u0131 g\xF6ster.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.enableNuanceTips).onChange(async (val) => {
        this.plugin.settings.enableNuanceTips = val;
        this.plugin.settings.enableSlangAlerts = val;
        await this.plugin.saveSettings();
      });
    });
  }
};

// src/llm/client.ts
var LLMClient = class {
  settings;
  constructor(settings) {
    this.settings = settings;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  getEndpoint() {
    if (this.settings.provider === "custom" && this.settings.customEndpoint.trim()) {
      return this.settings.customEndpoint.trim();
    }
    return PROVIDER_DEFAULTS[this.settings.provider].endpoint;
  }
  getModel() {
    if (this.settings.model.trim()) {
      return this.settings.model.trim();
    }
    return PROVIDER_DEFAULTS[this.settings.provider].defaultModel;
  }
  async testConnection() {
    try {
      const endpoint = this.getEndpoint();
      const model = this.getModel();
      const apiKey = this.settings.apiKey.trim();
      if (!apiKey && this.settings.provider !== "custom") {
        return {
          success: false,
          message: "API Key bo\u015F olamaz. L\xFCtfen ge\xE7erli bir anahtar girin."
        };
      }
      const headers = {
        "Content-Type": "application/json"
      };
      if (apiKey) {
        headers["Authorization"] = `Bearer ${apiKey}`;
      }
      if (this.settings.provider === "openrouter") {
        headers["HTTP-Referer"] = "https://obsidian.md";
        headers["X-Title"] = "Obsidian Fluency Bridge";
      }
      const res = await fetch(endpoint, {
        method: "POST",
        headers,
        body: JSON.stringify({
          model,
          messages: [{ role: "user", content: "Reply with 'OK' if you hear me." }],
          max_tokens: 100,
          temperature: 0.1
        })
      });
      if (!res.ok) {
        const errorText = await res.text();
        return {
          success: false,
          message: `API Hatas\u0131 (${res.status}): ${errorText.slice(0, 200)}`
        };
      }
      return {
        success: true,
        message: `Ba\u011Flant\u0131 ba\u015Far\u0131l\u0131! (${this.settings.provider.toUpperCase()} - ${model})`
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { success: false, message: `Ba\u011Flant\u0131 kurulamad\u0131: ${msg}` };
    }
  }
  async translateInFlow(expression, contextSentence) {
    const endpoint = this.getEndpoint();
    const model = this.getModel();
    const apiKey = this.settings.apiKey.trim();
    if (!apiKey && this.settings.provider !== "custom") {
      throw new Error(
        "Fluency Bridge API Anahtar\u0131 ayarlanmam\u0131\u015F! L\xFCtfen Eklenti Ayarlar\u0131ndan API anahtar\u0131n\u0131z\u0131 girin."
      );
    }
    const systemPrompt = `You are Fluency Bridge, an expert bilingual writing coach specialized in helping users write natural, fluent, and idiomatic ${this.settings.targetLanguage} while thinking in ${this.settings.nativeLanguage}.

The user is writing in ${this.settings.targetLanguage}, but hit a mental roadblock and wrote a phrase or word in [brackets] in ${this.settings.nativeLanguage}.

Your goals:
1. Provide the most natural, idiomatic, and contextually accurate ${this.settings.targetLanguage} replacement that fits seamlessly into the sentence's grammar, rhythm, and tone.
2. CONSTRUCTIVE FLUENCY & NUANCE COACHING:
   - Review the surrounding sentence for any typos (misspellings), unnatural collocations, or phrasing that could be expressed more clearly or idiomatically.
   - If there is a typo (e.g. "hearth" instead of "heart") or a phrase that would sound significantly more natural (e.g. "do research" instead of "make research"), provide a friendly, concise, and constructive tip in Turkish in the "feedback" field (e.g. "\u0130pucu: C\xFCmledeki 'make research' yerine 'do research' kullan\u0131m\u0131 daha do\u011Fald\u0131r.").
   - Do NOT lecture or moralize about tone or intent. Focus purely on constructive writing polish, clarity, and linguistic nuances.
   - If the sentence is already completely natural and error-free, set "feedback" to null.
3. Extract the key vocabulary item (word or collocation phrase) to add to the user's active vocabulary list.

You MUST respond strictly with valid JSON conforming to this schema (no markdown fences, no extra text):
{
  "replacement": "exact replacement string for inside or including the brackets",
  "feedback": "Optional concise, constructive tip in Turkish about typos, phrasing improvements, or nuance, or null",
  "vocabItem": {
    "term": "the key target language word or idiom",
    "definition": "T\xFCrk\xE7e anlam\u0131 ve kullan\u0131m notu",
    "example": "the full sentence with the replacement applied"
  }
}`;
    const userPrompt = `Context Sentence: "${contextSentence}"
Bracketed/Target Expression: "${expression}"

Provide the natural replacement to substitute the bracketed text directly.`;
    const headers = {
      "Content-Type": "application/json"
    };
    if (apiKey) {
      headers["Authorization"] = `Bearer ${apiKey}`;
    }
    if (this.settings.provider === "openrouter") {
      headers["HTTP-Referer"] = "https://obsidian.md";
      headers["X-Title"] = "Obsidian Fluency Bridge";
    }
    const payload = {
      model,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt }
      ],
      temperature: 0.2,
      max_tokens: 1024,
      response_format: { type: "json_object" }
    };
    const res = await fetch(endpoint, {
      method: "POST",
      headers,
      body: JSON.stringify(payload)
    });
    if (!res.ok) {
      const errText = await res.text();
      throw new Error(`LLM API Hatas\u0131 [${res.status}]: ${errText.slice(0, 300)}`);
    }
    const data = await res.json();
    const content = data.choices?.[0]?.message?.content;
    if (!content) {
      throw new Error("Modelden bo\u015F yan\u0131t al\u0131nd\u0131.");
    }
    let parsed;
    try {
      parsed = JSON.parse(content);
    } catch {
      const cleaned = content.replace(/```json\s*/g, "").replace(/```\s*$/g, "").trim();
      parsed = JSON.parse(cleaned);
    }
    parsed.feedback = parsed.feedback || parsed.warning || null;
    return parsed;
  }
};

// src/services/contextParser.ts
var ContextParser = class {
  /**
   * Extracts the target expression and surrounding context sentence from the active editor.
   */
  static extractTarget(editor) {
    const selection = editor.getSelection();
    const cursor = editor.getCursor();
    const lineNum = cursor.line;
    const lineText = editor.getLine(lineNum);
    if (selection && selection.trim().length > 0) {
      const from = editor.getCursor("from");
      const to = editor.getCursor("to");
      return {
        rawExpression: selection.trim(),
        fullSentence: lineText.trim() || selection.trim(),
        replaceRange: { from, to }
      };
    }
    const regex = /\[([^\]]+)\]/g;
    let match;
    const matches = [];
    while ((match = regex.exec(lineText)) !== null) {
      const start = match.index;
      const end = match.index + match[0].length;
      const innerContent = match[1];
      let distance = 0;
      if (cursor.ch < start) {
        distance = start - cursor.ch;
      } else if (cursor.ch > end) {
        distance = cursor.ch - end;
      } else {
        distance = 0;
      }
      matches.push({
        fullMatch: match[0],
        innerContent,
        start,
        end,
        distanceToCursor: distance
      });
    }
    if (matches.length === 0) {
      return null;
    }
    matches.sort((a, b) => a.distanceToCursor - b.distanceToCursor);
    const bestMatch = matches[0];
    return {
      rawExpression: bestMatch.innerContent,
      fullSentence: lineText.trim(),
      replaceRange: {
        from: { line: lineNum, ch: bestMatch.start },
        to: { line: lineNum, ch: bestMatch.end }
      }
    };
  }
};

// src/services/vocabulary.ts
var import_obsidian2 = require("obsidian");
var VocabularyManager = class {
  app;
  settings;
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  async logItem(result, originalSentence) {
    if (!this.settings.autoLogVocabulary || !result.vocabItem) {
      return false;
    }
    try {
      const filePath = (0, import_obsidian2.normalizePath)(this.settings.vocabularyPath.trim() || "Vocabulary.md");
      const folderPath = filePath.substring(0, filePath.lastIndexOf("/"));
      if (folderPath && !await this.app.vault.adapter.exists(folderPath)) {
        await this.app.vault.createFolder(folderPath);
      }
      const dateStr = (/* @__PURE__ */ new Date()).toISOString().slice(0, 16).replace("T", " ");
      const term = result.vocabItem.term.replace(/\|/g, "\\|");
      const def = result.vocabItem.definition.replace(/\|/g, "\\|");
      const sentence = (result.vocabItem.example || originalSentence).replace(/\|/g, "\\|").trim();
      const newRow = `| ${dateStr} | **${term}** | ${def} | ${sentence} |
`;
      const existingFile = this.app.vault.getAbstractFileByPath(filePath);
      if (existingFile instanceof import_obsidian2.TFile) {
        await this.app.vault.append(existingFile, newRow);
      } else {
        const initialContent = `# \u{1F4DA} Active Vocabulary Deck (Fluency Bridge)

Otomatik olu\u015Fturulan aktif kelime ve deyimler listesi.

| Tarih | \u0130fade / Kelime | Anlam & Not | Ba\u011Flamsal C\xFCmle |
| :--- | :--- | :--- | :--- |
` + newRow;
        await this.app.vault.create(filePath, initialContent);
      }
      return true;
    } catch (err) {
      console.error("[Fluency Bridge] Kelime kasas\u0131na kaydedilirken hata olu\u015Ftu:", err);
      return false;
    }
  }
};

// src/main.ts
var FluencyBridgePlugin = class extends import_obsidian3.Plugin {
  settings = DEFAULT_SETTINGS;
  llmClient = new LLMClient(this.settings);
  vocabManager = new VocabularyManager(this.app, this.settings);
  async onload() {
    await this.loadSettings();
    this.llmClient = new LLMClient(this.settings);
    this.vocabManager = new VocabularyManager(this.app, this.settings);
    this.addSettingTab(new FluencyBridgeSettingTab(this.app, this));
    this.addCommand({
      id: "replace-in-flow-expression",
      name: "Replace In-Flow Expression (Ak\u0131\u015F \u0130\xE7i \u0130fadeyi \xC7evir)",
      editorCallback: async (editor, _ctx) => {
        await this.handleInFlowTranslation(editor);
      },
      hotkeys: [
        {
          modifiers: ["Mod", "Shift"],
          key: "E"
        }
      ]
    });
    console.log("[Fluency Bridge] Eklenti ba\u015Far\u0131yla y\xFCklendi.");
  }
  onunload() {
    console.log("[Fluency Bridge] Eklenti devreden \xE7\u0131kar\u0131ld\u0131.");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    if (this.llmClient) {
      this.llmClient.updateSettings(this.settings);
    }
    if (this.vocabManager) {
      this.vocabManager.updateSettings(this.settings);
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.llmClient.updateSettings(this.settings);
    this.vocabManager.updateSettings(this.settings);
  }
  async handleInFlowTranslation(editor) {
    const target = ContextParser.extractTarget(editor);
    if (!target) {
      new import_obsidian3.Notice(
        "Fluency Bridge: \xC7evrilecek ifade bulunamad\u0131! L\xFCtfen bir ifadeyi [k\xF6\u015Feli parantez] i\xE7ine al\u0131n veya metni se\xE7in.",
        4e3
      );
      return;
    }
    const pendingNotice = new import_obsidian3.Notice(
      `Fluency Bridge: [${target.rawExpression}] ba\u011Flama g\xF6re d\xF6n\xFC\u015Ft\xFCr\xFCl\xFCyor...`,
      0
    );
    try {
      const startTime = performance.now();
      const result = await this.llmClient.translateInFlow(
        target.rawExpression,
        target.fullSentence
      );
      const durationMs = Math.round(performance.now() - startTime);
      pendingNotice.hide();
      if (!result.replacement) {
        new import_obsidian3.Notice("Fluency Bridge: Modelden ge\xE7erli bir kar\u015F\u0131l\u0131k al\u0131namad\u0131.", 4e3);
        return;
      }
      editor.replaceRange(
        result.replacement,
        target.replaceRange.from,
        target.replaceRange.to
      );
      const newCursorCh = target.replaceRange.from.ch + result.replacement.length;
      editor.setCursor({
        line: target.replaceRange.from.line,
        ch: newCursorCh
      });
      const tip = result.feedback || result.warning;
      const enableTips = this.settings.enableNuanceTips ?? this.settings.enableSlangAlerts ?? true;
      if (enableTips && tip) {
        new import_obsidian3.Notice(`\u{1F4A1} \u0130pucu: ${tip}`, 8e3);
      } else {
        new import_obsidian3.Notice(`\u2713 Ak\u0131\u015Fa uyarland\u0131 (${durationMs}ms)`, 2e3);
      }
      if (this.settings.autoLogVocabulary) {
        await this.vocabManager.logItem(result, target.fullSentence);
      }
    } catch (err) {
      pendingNotice.hide();
      const errorMsg = err instanceof Error ? err.message : String(err);
      new import_obsidian3.Notice(`Fluency Bridge Hatas\u0131: ${errorMsg}`, 7e3);
      console.error("[Fluency Bridge Error]", err);
    }
  }
};
